server:
  mode: debug
  addr: 7777
  readTimeout: 60
  writeTimeout: 60

aliYunOSS:
  endpoint: oss-cn-shenzhen-internal.aliyuncs.com
  accessKeyId: xxxxxxxxx
  accessKeySecret: xxxxxxxxx
  bucketName: xxx-xxxx
  bucketUrl: xxxxxx-xxxxx.oss-cn-xxxxx-internal.aliyuncs.com

